<a href="https://colab.research.google.com/github/gmazzitelli/studenti/blob/master/esempio_correlazione.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
import pandas as pd
a = [[1.0, 0.9, 0.7, 0.5, 0.1],
     [0.8, 1.0, 0.5, 0.2, 0.2],
     [0.6, 0.5, 1.0, 0.7, 0.5],
     [0.2, 0.7, 0.9, 1.0, 0.7],
     [0.2, 0.5, 0.8, 0.9, 1.0]]
a = np.array(a)
df = pd.DataFrame(a, columns = ['A','B','C', 'E','F'])

In [56]:
df

A    B    C    E    F
0  1.0  0.9  0.7  0.5  0.1
1  0.8  1.0  0.5  0.2  0.2
2  0.6  0.5  1.0  0.7  0.5
3  0.2  0.7  0.9  1.0  0.7
4  0.2  0.5  0.8  0.9  1.0

In [57]:
df.values   # trasformi gli elementi della matrice di correlazione in un array

array([[1. , 0.9, 0.7, 0.5, 0.1],
       [0.8, 1. , 0.5, 0.2, 0.2],
       [0.6, 0.5, 1. , 0.7, 0.5],
       [0.2, 0.7, 0.9, 1. , 0.7],
       [0.2, 0.5, 0.8, 0.9, 1. ]])

In [79]:
b = a<=0.2  # correlati al 80%
b           # matrice dei valori che rispettano la condizione

array([[False, False, False, False,  True],
       [False, False, False,  True,  True],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False]])

In [80]:
c = b*a     # ottieni i valori che verificano la condiziome

In [81]:
c

array([[0. , 0. , 0. , 0. , 0.1],
       [0. , 0. , 0. , 0.2, 0.2],
       [0. , 0. , 0. , 0. , 0. ],
       [0.2, 0. , 0. , 0. , 0. ],
       [0.2, 0. , 0. , 0. , 0. ]])

In [82]:
ds = pd.DataFrame(c, columns = ['A','B','C', 'E','F'])  # se vuoi ti ricostruisci la matrce di correlazione

In [83]:
ds # sopravvivono solo le correlazioni al 80%

A    B    C    E    F
0  0.0  0.0  0.0  0.0  0.1
1  0.0  0.0  0.0  0.2  0.2
2  0.0  0.0  0.0  0.0  0.0
3  0.2  0.0  0.0  0.0  0.0
4  0.2  0.0  0.0  0.0  0.0

In [84]:
m2 = (ds != 0).any()

In [85]:
m2

A     True
B    False
C    False
E     True
F     True
dtype: bool

In [87]:
m3 = (df <= 0.2).any()

In [88]:
m3

A     True
B    False
C    False
E     True
F     True
dtype: bool