<a href="https://colab.research.google.com/github/gmazzitelli/studenti/blob/master/esempio_correlazione.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd
a = [[1.0, 0.9, 0.7, 0.5, 0.1],
     [0.8, 1.0, 0.5, 0.2, 0.2],
     [0.6, 0.5, 1.0, 0.7, 0.5],
     [0.2, 0.7, 0.9, 1.0, 0.7],
     [0.2, 0.5, 0.8, 0.9, 1.0]]
a = np.array(a)
df = pd.DataFrame(a, columns = ['A','B','C', 'E','F'])

In [37]:
df

A    B    C    E    F
0  1.0  0.9  0.7  0.5  0.1
1  0.8  1.0  0.5  0.2  0.2
2  0.6  0.5  1.0  0.7  0.5
3  0.2  0.7  0.9  1.0  0.7
4  0.2  0.5  0.8  0.9  1.0

In [39]:
df.values   # trasformi gli elementi della matrice di correlazione in un array

array([[1. , 0.9, 0.7, 0.5, 0.1],
       [0.8, 1. , 0.5, 0.2, 0.2],
       [0.6, 0.5, 1. , 0.7, 0.5],
       [0.2, 0.7, 0.9, 1. , 0.7],
       [0.2, 0.5, 0.8, 0.9, 1. ]])

In [50]:
b = a<=0.1  # correlati al 90%
b           # matrice dei valori che rispettano la condizione

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [51]:
c = b*a     # ottieni i valori che verificano la condiziome

In [52]:
c

array([[0. , 0. , 0. , 0. , 0.1],
       [0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. ]])

In [53]:
ds = pd.DataFrame(c, columns = ['A','B','C', 'E','F'])  # se vuoi ti ricostruisci la matrce di correlazione

In [54]:
ds # l'unica correlazione che sopravive al tuo taglio e' A con F che quindi sono scorrelate al 90%

A    B    C    E    F
0  0.0  0.0  0.0  0.0  0.1
1  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0